### ISSUE TITLE
update travis config

### ISSUE THREAD

**Issue by cdiener** [opencobra/optlang#137]
Hi,

I think it would be helpful if travis could also run the tests for symengine and Python 3.6.

**Comment by KristianJensen** [comment]
I completely agree. This probably requires that the travis setup is changed to use anaconda. I'm not a travis expert so I don't know how easy that is to change?

All in all the testing scheme should be updated on several fronts:
 - Include tests of symengine
 - Remove testing on python 3.4
 - Add testing on python 3.6
 - Upgrade to a newer version of cplex
 - Add testing of gurobi

**Comment by cdiener** [comment]
I would be happy to help out with that :)

3.6 is [available on travis](https://docs.travis-ci.com/user/languages/python/). Just have to add it to the build matrix. I think for symengine it would be as easy as installing it and running the tests once with symengine on and another time with it being off. 

Gurobi may be complicated since you would need to acquire a key on the travis machine. It may also violate licensing terms...

**Comment by KristianJensen** [comment]
Can symengine be installed with pip now? Last I checked it could only be installed through conda or from source.

**Comment by cdiener** [comment]
Yes, symengine now has wheels for all platforms!

**Comment by KristianJensen** [comment]
That's great! WIP is here https://github.com/biosustain/optlang/tree/update-travis-testing
You're right that cplex/gurobi are the only non-trivial changes

Once symengine is automatically tested (and passes) I guess we can make symengine support official

**Comment by cdiener** [comment]
I have currently learned that there is a community version of cplex (only supports models up to 1000 vars). Will investigate if that works here....

**Comment by cdiener** [comment]
Hmmm. I checked the community edition and you still need an IBM ID to download, so there is not automatic download and probably also no permission to provide a public download...
