### ISSUE TITLE
[feature request] absolute values in linear programming

### ISSUE THREAD

**Issue by pstjohn** [opencobra/optlang#142]
I know this is listed on the 'future work' section of the readme, but I'll echo support for this feature. It would be great to port code like the following from cobrapy to optlang eventually

https://github.com/opencobra/cobrapy/blob/17b5b77494c3bacd6b51419e681530800ec8013a/cobra/util/solver.py#L324-L368

**Comment by KristianJensen** [comment]
That's a pretty cool trick. In most cases I think the same can be achieved without adding a new variable, but conceptually this makes it simpler.
I would not be opposed to having a suite of utility functions (separate from the current util module which is mostly low level internal stuff) to perform things like this.

**Comment by cdiener** [comment]
The variable is only created because this allows you to use it in the objective expression which is the use case we have in cobrapy. The limitation with that method is that it *only* works for minimization problems and will fail completely when used for maximization where you need a MILP formulation to achieve absolute values.

**Comment by pstjohn** [comment]
Good call! although that's probably a use case that's fairly common.

https://optimization.mccormick.northwestern.edu/index.php/Optimization_with_absolute_values

In particular, one problem I'm dealing with now is related to the method they used in [this paper](dx.doi.org/10.1126/science.aaf2786), which essentially does quadratic programming to find the most likely flux distribution together with FVA to find feasible regions for those fluxes.

With the current optlang, doing FVA is tricky since optlang doesn't support a quadratic constraint (i.e., holding the QP-objective at a constant value) while maximizing/minimizing other reactions. And so I was considering using absolute values with @cdiener's method. Although I'm not sure that translates well between objective and constraint.

**Comment by KristianJensen** [comment]
You should be able to use this method for what you describe. When you minimize an absolute value that can be translated to an upper bound constraint, which is also valid with this implementation.

A function that constrains lower bounds on absolute values would be another good candidate for a utility module.

**Comment by cdiener** [comment]
Closing for now since we have that functionality in cobrapy now.
