### ISSUE TITLE
[planned feature] add interface for OSQP

### ISSUE THREAD

**Issue by cdiener** [opencobra/optlang#203]
This is just an announcement of intent. I have recently looked into [OSQP](https://OSQP.org) for use in micom as a QP solver suitable for large systems 
and it looks decent. It is a bit slower than cplex or gurobi (about 10x) for bad problems but is robust and decently accurate. Package itself is pip or conda installable so it should be doable. One drawback is that it does not have a dedicated LP solver (you can solve LPs but it is less efficient than "real" ones). Still a good addition I would say.

**Comment by KristianJensen** [comment]
This looks very nice. An open source QP solver would definitely be a good addition.
