### ISSUE TITLE
Can we get a new release?

### ISSUE THREAD

**Issue by cdiener** [opencobra/optlang#207]
Last optlang release is over a year old and there have been a few bug fixes that affect us on the cobrapy side, in particular the ones in #202.

Thanks!

**Comment by Midnighter** [comment]
There is https://github.com/biosustain/optlang/pull/206 which seems stale now. I will ask Niko on what to do.

**Comment by KristianJensen** [comment]
Yes, I made #206 a while ago, but I ran into a technical issue and completely forgot about it

**Comment by KristianJensen** [comment]
@phantomas1234 I've merged #206 but travis fails to deploy to PyPI with a "Bad credentials" error. Can you check whether this is easily fixable?

**Comment by Midnighter** [comment]
I guess it has to do with Niko leaving CfB. Maybe migrating optlang to opencobra is the better long term solution?

**Comment by matthiaskoenig** [comment]
Can we please get a new release?

**Comment by matthiaskoenig** [comment]
@Midnighter thanks so much. This is great.
