### ISSUE TITLE
[BUG] Can't load salmonella test model in cobrapy

### ISSUE THREAD

**Issue by braceal** [opencobra/optlang#214]
Steps to reproduce:

install optlangs devel branch.
git clone https://github.com/opencobra/cobrapy.git
Comment out the specific optlang version requirement in cobrapy/setup.py
Run pip install -e . from cobrapy/
Open the python interpreter and run:
![image](https://user-images.githubusercontent.com/38300604/85146002-66655700-b21b-11ea-93d2-91f5e60c37ee.png)

This error seems to occur from master and devel branches in cobrapy. It happens when cobrapy reads a pickled model file containing salmonella.

I can get the code to run if I add an if statement checking that "tolerances" is in state, but I'm not sure if this will introduce other bugs. @cdiener @KristianJensen What do y'all think?

![image](https://user-images.githubusercontent.com/38300604/85146993-34a0c000-b21c-11ea-83f4-5a056e0ba44f.png)

**Comment by cdiener** [comment]
Stumbled over the same thing. I also have a fix for that one in the OSQP branch in the optlang PR if you want to migrate it.

**Comment by braceal** [comment]
I currently have a branch (linked below) with your OSQP solver and the CBC solver where I am testing everything out. After fixing this bug (temporarily with the if statement) things seem to be running again. But I think you are right, it is just a version issue with the pickle file in cobrapy so the the if statement will not be necessary after the update. So far I have been testing with textbook, ecoli and salmonella. Are there any others you recommend, good benchmarks for moma, fva, fba?

**Comment by cdiener** [comment]
Those seem okay. I would test a handful of problems from MIPLIB since they have reference solutions. You could even add a few to the test suite.
