### ISSUE TITLE
Changelog information in release does not exist

### ISSUE THREAD

**Issue by matthiaskoenig** [opencobra/optlang#224]
The following file does not exist
https://github.com/opencobra/optlang/blob/a7c02b21b702d1f1dfce7f45f36a824bdb354ddb/.github/workflows/main.yml#L88
As a consequence the changelog link is dead in the release information. Could not find any changelog information otherwise I would have created a pull request.

**Comment by Midnighter** [comment]
Cheers, yes that's from my cookiecutter template. @KristianJensen were you writing release notes directly on GitHub previously?

**Comment by KristianJensen** [comment]
Yes, I've been logging changes in the commit messages on the master branch
