### ISSUE TITLE
Feasibility and optimality violation in QP problems

### ISSUE THREAD

**Issue by Midnighter** [opencobra/optlang#227]
> Dear All,
> 
> some time ago, within the cobra toolbox, I implemented checks on
> satisfaction of feasibility and optimality criteria to test that (a)
> all solvers returned their solution, including dual variables, in a
> consistent manner (esp with respect to signs of dual variables) and
> (b) that any failure to return a feasible and optimal solution (within
> the feasibility and optimality tolerance specified) would be detected.
> 
> Recently I opened a support request with gurobi concerning their QP
> solver because I and others were having issues with optimality
> conditions apparently not being satisfied by possibly atypical QP
> problems arising from M-models. Gurobi has confirmed there is an issue
> on their side and is looking into it. Here is a key extract from their
> response:
> 
> "Gurobi solves a scaled version of the QP and finds a solution that
> doesn't violate the (scaled) constraints by any meaningful amount.
> However, after the model and solution are unscaled, the violation
> increases quite a bit. Our developers are aware of the issue and are
> currently investigating. As such, I'll close this ticket. I'll reach
> out to you if/when this is fixed in a future Gurobi release. In the
> meantime, solving with barrier (Method=2) or disabling scaling
> (ScaleFlag=0) should resolve the issue."
> 
> Michael Saunders, Ines Thiele and I had seen the same problem
> previously with LP problems arising from ME-models, even with
> supposedly the best industrial double precision LP solvers. Together
> with Prof. Palsson we developed quad precision solvers to handle the
> worst instances (https://www.nature.com/articles/srep40863) but they
> are currently slower as they use software to imitate quad precision on
> a double precision machine. Some double precision solvers, e.g.,
> ibm_cplex, have no problem with the QP example that gurobi had
> problems with, but they are not immune to scaling problems if the
> problem is sufficiently ill-scaled.
> 
> I have reviewed some of the interfaces to gurobi from the growing
> number of separate, :( , packages that are doing various aspects of
> COBRA and also call gurobi and I thus far I have not found explicit
> tests for feasibility and optimality criteria so it may be that this
> previously occult issue could be affecting modelling results for
> occult ill-scaled models.
> e.g. cobrapy
> https://github.com/opencobra/optlang/blob/master/src/optlang/gurobi_interface.py
> e.g. polyround
> https://gitlab.com/csb.ethz/PolyRound/-/blob/master/PolyRound/static_classes/gurobi_lp.py
> e.g. cobamp
> https://github.com/BioSystemsUM/cobamp/blob/master/src/cobamp/core/optimization.py
> e.g. sybilgurobi
> https://gitlab.cs.uni-duesseldorf.de/general/ccb/sybilGUROBI/-/blob/master/R/optObj_sybilGUROBIClass.R
> 
> I think it would be a good idea for all COBRA software to implement
> feasibility and optimality tests after calling any solver in routine
> use. It is highly likely that gurobi's QP solver is not the only
> solver having issues with scaling.
> 
> An equally important point is that we do not, to my knowledge, have
> criteria that are in routine use to alert us to situations when a
> given model is sufficiently ill-scaled as to pose a risk for double
> precision solver failure. Previously, for cobra toolbox v3.0 we tried
> to define well-scaled and ill-scaled by the ratio of the non-zero
> singular values of the stoichiometric matrix
> (https://opencobra.github.io/cobratoolbox/stable/tutorials/tutorialNumCharact.html)
> however that approach seems incomplete because the ability to be
> solved or not, with a double precision solver, can often also depend
> on the bounds and/or objective. It would be interesting to hear others
> thoughts as to how we might define ill-scaled.
> 
> At present, I think it is highly likely that there are a subset of
> ill-scaled models, operationally defined as models unsuitable for a
> double precision solver, contained within widely used model
> repositories and that there are unwitting end users relying on
> incorrect or suboptimal solutions arising from double precision
> solvers.
> 
> I think it would be good if we could work together toward solutions to
> these problems as a cooperative community. Please share this message
> with your colleagues who may be interested.
> 
> Regards,
> 
> Ronan
> 
> 
> The implementation of feasibility and optimality tests for QP problems
> in the cobra toolbox are here:
> https://github.com/opencobra/cobratoolbox/blob/800dcfe40dcd298fce347bb9dc72a74f4bff09a3/src/base/solvers/solveCobraQP.m#L1036
> The implementation of feasibility and optimality tests for LP problems
> in the cobra toolbox are here:
> https://github.com/opencobra/cobratoolbox/blob/800dcfe40dcd298fce347bb9dc72a74f4bff09a3/src/base/solvers/solveCobraLP.m#L1623

**Comment by cdiener** [comment]
I'll close that for now. Axel Theorell actually ran checks with optlang and presented the results in the [Gitter chat](https://gitter.im/biosustain/optlang). No tolerance violations were detected for optlang, so it looks like it is not an issue here.
