### ISSUE TITLE
Parallelize large LP's

### ISSUE THREAD

**Issue by freiburgermsu** [opencobra/optlang#247]
### Checklist

- [x ] I searched the [documentation](https://optlang.readthedocs.io).
- [ x] I looked through [similar issues on GitHub](https://github.com/opencobra/optlang/issues).
- [x ] I looked up "How to do ... in optlang" on a search engine.

### Question

Hello,

I am developing large LP's that, in the base case, require ~1.5 days to solve. Is there a means of parallelizing the optimization to leverage server/supercomputer architectures in Optlang? [PuLP seems to offer some of the desired functionality](https://towardsdatascience.com/linear-programming-using-python-priyansh-22b5ee888fe0), but I would prefer to stay within Optlang since it is the default environment for our COBRApy models.

Thank you :)
    Andrew

**Comment by cdiener** [comment]
You can use multiple cores if the solver backend allows it. For instance with cplex or gurobi. Is that pure LP or MILP? For LPs switching to an interior point method will also speed up optimizations a lot...

**Comment by freiburgermsu** [comment]
Hello!      

It's an MILP, but I will remember the interior point method sluggish LP models. Thank you for reminding me that solvers handle parallelization as well. I found [a nice tutorial for Gurobi](https://support.gurobi.com/hc/en-us/articles/360043111231-How-do-I-use-multiprocessing-in-Python-with-Gurobi-). 

:) Andrew

**Comment by cdiener** [comment]
Oh yeah, that would work for several MILPs. But you can also do something like this for a Gurobi model in optlang to parallelize a single model:

```python
model.problem.Params.Threads = 8
```
