### ISSUE TITLE
Default solvers

### ISSUE THREAD

**Issue by Midnighter** [opencobra/optlang#257]
At the moment, swiglpk is one of the dependencies. I was wondering if osqp, mip, highspy shall also be default dependencies?

**Comment by cdiener** [comment]
It's a good question. There are some issues with upstream packages breaking or not updating to new Python versions which could hold optlang back. For instance, highspy currently has no working MAC wheel.

**Comment by Midnighter** [comment]
Although conda might alleviate some of those issues. Let's revisit when we create a dedicated HIGHS interface and make it default.
