### ISSUE TITLE
constraint.problem is not always being reset in _remove_constraints of Model

### ISSUE THREAD

**Issue by axelvonkamp** [opencobra/optlang#271]
In _remove_constraints there is a branch when the number of constraints to be removed is > 350 (line 1578 in interface.py). When this is the case the constraints are removed but their problem attribute is not being set to None (as is being done in the else branch). This leads to an error when a list of more than 350 constraints is being added, then removed, and then being added again.
Adding a simple loop
```
for c in constraints:
    c.problem = None
```
to the if branch will resolve this bug.

**Comment by cdiener** [comment]
Good catch! I will send in a fix.
