### ISSUE TITLE
catching solver-specific errors and re-raising with a common optlang error

### ISSUE THREAD

**Issue by Midnighter** [opencobra/optlang#75]
My current problem in cobrapy is that when `Reaction.flux` is accessed before optimization, I get solver-specific errors, like `CplexSolverError` or `GurobiError`. These are raised when accessing `optlang.Variable.primal`, for example. I was wondering whether `optlang`, which is aware of the solvers available, could catch these and raise a unified `optlang.SolverError` (or similar) instead.

The problem is that cobrapy is not explicitly aware of the solvers available so I cannot import the errors in order to catch them specifically.

**Comment by KristianJensen** [comment]
That would be possible. However you should be aware that the solvers have different behaviour in this case (accessing primals in a problem that is unsolved/changed) which falls outside the documented optlang interface.

**Comment by KristianJensen** [comment]
@Midnighter Are there still any solver errors that are not being caught, which you think should be? Or can I close this?

**Comment by Midnighter** [comment]
@hredestig asked me the exact same question yesterday :smile: I looked into my PR and we're only doing this for the `CplexSolverError`s at the moment. I would like to do the same for `GurobiError`s before closing this issue.
